# Generated by Django 5.2.5 on 2025-08-29 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analisis", "0002_palabra"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="palabra",
            options={"ordering": ["-frecuencia"]},
        ),
    ]
