# Generated by Django 5.2.5 on 2025-09-02 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analisis", "0003_alter_palabra_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="textoanalizado",
            name="n_grama",
            field=models.IntegerField(
                default=1,
                help_text="Tamaño del n-grama (1 = palabras, 2 = bigramas, 3 = trigramas, etc.)",
            ),
        ),
        migrations.AlterField(
            model_name="palabra",
            name="contenido",
            field=models.CharField(max_length=200),
        ),
    ]
